### ISSUE TITLE
Autogenerate a master list of all services and resource types

### ISSUE THREAD

**Issue by parth-dassana** [dassana-io/dassana#128]
AWS has done a good job listing all possible arns in one location: https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonec2.html

We need to scrape each service for the arn and then we need to autogenerate a resource-hierarchy of csp -> service -> resource type as AWS identifies it.

For some services like S3, SQS, and SNS there is no concept of resource type in the arn. In such cases, we should still define a resource type even though it is not used in the arn.

Here is a link to what the schema should look like: https://github.com/dassana-io/dassana/blob/main/content/schemas/resource-hierarchy/resource-hierarchy.yaml

**Comment by gauravphoenix** [comment]
Here is an enhanced version - 
```yaml
services: 
 - id: "s3"
   name: "s3"
   resource-types:
    - id: ''
      name: "bucket"
    - id: "accesspoint"
      name: 'access point'

 - id: "sqs"
   name: "sqs"
   resource-types:
    - id: ''
      name: "queue"

 - id: "sns"
   name: "sns"
   resource-types:
    - id: ''
      name: 'topic'
```

There isn't a lot of value in having `name` field, but we should make `resource-types` as a first-class citizen so that in future we can easily add meta-data to services. Today we only have `resource-types` but in the future we may have more things to be represented for a service (e.g. console URL etc.)

The consumers of this file should always use the `id` value and the `name` value can be more of a _display field_. If `name` is missing, use `id`
