### ISSUE TITLE
Support subrules for the risk config

### ISSUE THREAD

**Issue by parth-dassana** [dassana-io/dassana#288]
I should be able to do something along the lines of:

```
risk-config:
  default-risk: ""
  rules:
    - id: prod-environment-risk-is-high
      condition: .tags | any( select(.name | test("env" ; "ix")) | select(.value | test("prod" ; "ix")))
      risk: high
      subrules:
        - id: iam-networking-are-critical
           condition: alertClassification.category == "iam" or alertClassification.category == "networking"
           risk: critical
        - id: encryption-is-not-important
           condition: alertClassification.category == "storage"  and alertClassification.subcategory == "encryption"
           risk: medium
```
