### ISSUE TITLE
Rule Grouping + Evaluate All Rules

### ISSUE THREAD

**Issue by parth-dassana** [dassana-io/dassana#389]
Current

```
rules:
  - id: xxx
    condition:
    risk:
  - ...
```

Future:
```
rules:
  - id:
   condition:
   subrules:
      - id:
        condition:
        risk:
```

We also want to evaluate all rules and use the most severe one for risk assignment instead of exit on first match.
