### ISSUE TITLE
EC2 Exposure

### ISSUE THREAD

**Issue by parth-dassana** [dassana-io/dassana#67]
Currently we have a lot of actions that check things like
- is instance behind a load balancer
- is load balacer tracking a target group
- is target group part of autoscaling group

We had added these actions with one goal: figure out the exposure of an EC2 instance. Let's refactor the actions so that there is a single action to take care of finding the exposure of an ec2 instance.

The output of the action should be something along the lines of:
```
exposure:
    appLayer:
        type: alb
        auth:
            type: authenticate-cognito | authenticate-oidc
    direct:
        publicIp:
        allowedVia:
            sg:
                id:
```

appLayer: This is specifically about load balancers. First figure out if it is internal or public. For now only do alb. Look at load balancer -> listener -> action for how auth is handled.

direct:
    publicIp: does EC2 instance have a public IP? If so, post it.
    allowedVia: based on whatever the ec2 instance is attached to.
